// Code generated by "go-sumtypes/generate.go". DO NOT EDIT.

package sum3

import "reflect"

type Type[T0, T1, T2 any] struct {
	v any
}

func (s *Type[T0, T1, T2]) Set0(v T0) {
	s.v = v
}

func (s Type[T0, T1, T2]) As0() (T0, bool) {
	v, ok := s.v.(T0)
	return v, ok
}

func (s *Type[T0, T1, T2]) Set1(v T1) {
	s.v = v
}

func (s Type[T0, T1, T2]) As1() (T1, bool) {
	v, ok := s.v.(T1)
	return v, ok
}

func (s *Type[T0, T1, T2]) Set2(v T2) {
	s.v = v
}

func (s Type[T0, T1, T2]) As2() (T2, bool) {
	v, ok := s.v.(T2)
	return v, ok
}

func (s Type[T0, T1, T2]) Case(f0 func(T0), f1 func(T1), f2 func(T2)) {
	switch v := s.v.(type) {
	case T0:
		if f0 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f0(v)
	case T1:
		if f1 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f1(v)
	case T2:
		if f2 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f2(v)
	default:
		panic("called Case on an invalid value")
	}
}
