// Code generated by "go-sumtypes/generate.go". DO NOT EDIT.

package sum2

import "reflect"

type Type[T0, T1 any] struct {
	v any
}

func (s *Type[T0, T1]) Set0(v T0) {
	s.v = v
}

func (s Type[T0, T1]) Get0() (T0, bool) {
	v, ok := s.v.(T0)
	return v, ok
}

func (s *Type[T0, T1]) Set1(v T1) {
	s.v = v
}

func (s Type[T0, T1]) Get1() (T1, bool) {
	v, ok := s.v.(T1)
	return v, ok
}

func (s Type[T0, T1]) Case(f0 func(T0), f1 func(T1)) {
	switch v := s.v.(type) {
	case T0:
		if f0 == nil {
			noHandler(v)
		}
		f0(v)
	case T1:
		if f1 == nil {
			noHandler(v)
		}
		f1(v)
	default:
		panic("called Case on an invalid value")
	}
}

func noHandler(v any) {
	panic("no handler for case " + reflect.TypeOf(v).String())
}
