// Code generated by "go-sumtypes/generate.go". DO NOT EDIT.

package sum13

type Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 any] struct {
	v any
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set0(v T0) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New0(v T0) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As0() (T0, bool) {
	v, ok := s.v.(T0)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set1(v T1) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New1(v T1) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As1() (T1, bool) {
	v, ok := s.v.(T1)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set2(v T2) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New2(v T2) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As2() (T2, bool) {
	v, ok := s.v.(T2)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set3(v T3) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New3(v T3) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As3() (T3, bool) {
	v, ok := s.v.(T3)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set4(v T4) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New4(v T4) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As4() (T4, bool) {
	v, ok := s.v.(T4)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set5(v T5) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New5(v T5) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As5() (T5, bool) {
	v, ok := s.v.(T5)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set6(v T6) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New6(v T6) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As6() (T6, bool) {
	v, ok := s.v.(T6)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set7(v T7) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New7(v T7) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As7() (T7, bool) {
	v, ok := s.v.(T7)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set8(v T8) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New8(v T8) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As8() (T8, bool) {
	v, ok := s.v.(T8)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set9(v T9) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New9(v T9) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As9() (T9, bool) {
	v, ok := s.v.(T9)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set10(v T10) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New10(v T10) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As10() (T10, bool) {
	v, ok := s.v.(T10)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set11(v T11) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New11(v T11) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As11() (T11, bool) {
	v, ok := s.v.(T11)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Set12(v T12) {
	s.v = v
}

func (*Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) New12(v T12) Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] {
	return Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]{v}
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) As12() (T12, bool) {
	v, ok := s.v.(T12)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Underlying() any {
	return s.v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]) Case(f0 func(T0), f1 func(T1), f2 func(T2), f3 func(T3), f4 func(T4), f5 func(T5), f6 func(T6), f7 func(T7), f8 func(T8), f9 func(T9), f10 func(T10), f11 func(T11), f12 func(T12)) {
	switch v := s.v.(type) {
	case T0:
		f0(v)
	case T1:
		f1(v)
	case T2:
		f2(v)
	case T3:
		f3(v)
	case T4:
		f4(v)
	case T5:
		f5(v)
	case T6:
		f6(v)
	case T7:
		f7(v)
	case T8:
		f8(v)
	case T9:
		f9(v)
	case T10:
		f10(v)
	case T11:
		f11(v)
	case T12:
		f12(v)
	default:
		panic("called Case on an invalid value")
	}
}
