// Code generated by "go-sumtypes/generate.go". DO NOT EDIT.

package sum16

import "reflect"

type Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 any] struct {
	v any
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set0(v T0) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As0() (T0, bool) {
	v, ok := s.v.(T0)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set1(v T1) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As1() (T1, bool) {
	v, ok := s.v.(T1)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set2(v T2) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As2() (T2, bool) {
	v, ok := s.v.(T2)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set3(v T3) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As3() (T3, bool) {
	v, ok := s.v.(T3)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set4(v T4) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As4() (T4, bool) {
	v, ok := s.v.(T4)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set5(v T5) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As5() (T5, bool) {
	v, ok := s.v.(T5)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set6(v T6) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As6() (T6, bool) {
	v, ok := s.v.(T6)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set7(v T7) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As7() (T7, bool) {
	v, ok := s.v.(T7)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set8(v T8) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As8() (T8, bool) {
	v, ok := s.v.(T8)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set9(v T9) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As9() (T9, bool) {
	v, ok := s.v.(T9)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set10(v T10) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As10() (T10, bool) {
	v, ok := s.v.(T10)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set11(v T11) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As11() (T11, bool) {
	v, ok := s.v.(T11)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set12(v T12) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As12() (T12, bool) {
	v, ok := s.v.(T12)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set13(v T13) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As13() (T13, bool) {
	v, ok := s.v.(T13)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set14(v T14) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As14() (T14, bool) {
	v, ok := s.v.(T14)
	return v, ok
}

func (s *Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Set15(v T15) {
	s.v = v
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) As15() (T15, bool) {
	v, ok := s.v.(T15)
	return v, ok
}

func (s Type[T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]) Case(f0 func(T0), f1 func(T1), f2 func(T2), f3 func(T3), f4 func(T4), f5 func(T5), f6 func(T6), f7 func(T7), f8 func(T8), f9 func(T9), f10 func(T10), f11 func(T11), f12 func(T12), f13 func(T13), f14 func(T14), f15 func(T15)) {
	switch v := s.v.(type) {
	case T0:
		if f0 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f0(v)
	case T1:
		if f1 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f1(v)
	case T2:
		if f2 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f2(v)
	case T3:
		if f3 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f3(v)
	case T4:
		if f4 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f4(v)
	case T5:
		if f5 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f5(v)
	case T6:
		if f6 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f6(v)
	case T7:
		if f7 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f7(v)
	case T8:
		if f8 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f8(v)
	case T9:
		if f9 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f9(v)
	case T10:
		if f10 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f10(v)
	case T11:
		if f11 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f11(v)
	case T12:
		if f12 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f12(v)
	case T13:
		if f13 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f13(v)
	case T14:
		if f14 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f14(v)
	case T15:
		if f15 == nil {
			panic("no handler for case " + reflect.TypeOf(v).String())
		}
		f15(v)
	default:
		panic("called Case on an invalid value")
	}
}
