// Code generated by "github.com/win-t/go-sumtypes". DO NOT EDIT.

package machine
func(Print)sumtype(){}
func(s Print)Case(f func(Print),_ func(PushInt),_ func(Add),_ func(Exit)){f(s)}
func(PushInt)sumtype(){}
func(s PushInt)Case(_ func(Print),f func(PushInt),_ func(Add),_ func(Exit)){f(s)}
func(Add)sumtype(){}
func(s Add)Case(_ func(Print),_ func(PushInt),f func(Add),_ func(Exit)){f(s)}
func(Exit)sumtype(){}
func(s Exit)Case(_ func(Print),_ func(PushInt),_ func(Add),f func(Exit)){f(s)}